import type { Chain } from './chains';

export const EXPANDED_CHAIN_CONFIG: Record<string, Chain> = {
  // APTOS
  'aptos:mainnet': {
    id: 'aptos:mainnet' as any,
    name: 'Aptos Mainnet',
    symbol: 'APT',
    type: 'aptos',
    icon: '/icons/chains/aptos.svg',
    rpcUrl: 'https://fullnode.mainnet.aptoslabs.com/v1',
    explorerUrl: 'https://explorer.aptoslabs.com',
    nativeCurrency: { name: 'Aptos', symbol: 'APT', decimals: 8 },
    isTestnet: false,
    isEnabled: true,
    priority: 49,
    status: 'healthy',
    chainId: 1,
    gasConfig: { type: 'move', gasUnitPrice: 100, maxGasAmount: 100000 },
    features: { programmableObjects: true, parallelExecution: true },
  },

  // MOVEMENT
  'movement:mainnet': {
    id: 'movement:mainnet' as any,
    name: 'Movement Mainnet',
    symbol: 'MOVE',
    type: 'movement',
    icon: '/icons/chains/movement.svg',
    rpcUrl: 'https://mainnet.movement.xyz/api/v1/rpc',
    explorerUrl: 'https://explorer.movement.xyz',
    nativeCurrency: { name: 'Movement', symbol: 'MOVE', decimals: 8 },
    isTestnet: false,
    isEnabled: true,
    priority: 50,
    status: 'healthy',
    gasConfig: { type: 'move', gasUnitPrice: 100, maxGasAmount: 100000 },
    features: { programmableObjects: true, moveCompatibility: true, cosmosInterop: true },
  },

  // SOLANA ECOSYSTEM
  'sonic:mainnet': {
    id: 'sonic:mainnet' as any,
    name: 'Sonic',
    symbol: 'S',
    type: 'solana',
    icon: '/icons/chains/sonic.svg',
    rpcUrl: 'https://rpc.sonic.game',
    explorerUrl: 'https://explorer.sonic.game',
    nativeCurrency: { name: 'Sonic', symbol: 'S', decimals: 9 },
    isTestnet: false,
    isEnabled: true,
    priority: 51,
    status: 'healthy',
    gasConfig: { type: 'solana', lamportsPerSignature: 5000 },
    features: { spl: true, gaming: true },
  },

  'eclipse:mainnet': {
    id: 'eclipse:mainnet' as any,
    name: 'Eclipse',
    symbol: 'ECL',
    type: 'solana',
    icon: '/icons/chains/eclipse.svg',
    rpcUrl: 'https://mainnetbeta-rpc.eclipse.xyz',
    explorerUrl: 'https://explorer.eclipse.xyz',
    nativeCurrency: { name: 'Eclipse', symbol: 'ECL', decimals: 9 },
    isTestnet: false,
    isEnabled: true,
    priority: 52,
    status: 'healthy',
    gasConfig: { type: 'solana', lamportsPerSignature: 5000 },
    features: { spl: true, modular: true },
  },

  // COSMOS ECOSYSTEM
  'osmosis:mainnet': {
    id: 'osmosis:mainnet' as any,
    name: 'Osmosis',
    symbol: 'OSMO',
    type: 'cosmos',
    icon: '/icons/chains/osmosis.svg',
    rpcUrl: 'https://rpc.cosmos.directory/osmosis',
    explorerUrl: 'https://www.mintscan.io/osmosis',
    nativeCurrency: { name: 'Osmosis', symbol: 'OSMO', decimals: 6 },
    isTestnet: false,
    isEnabled: true,
    priority: 53,
    status: 'healthy',
    gasConfig: { type: 'cosmos', gasPrice: '0.0025uosmo', gasLimit: 200000 },
    features: { cosmwasmEnabled: true, ibc: true, dex: true },
  },

  'injective:mainnet': {
    id: 'injective:mainnet' as any,
    name: 'Injective',
    symbol: 'INJ',
    type: 'cosmos',
    icon: '/icons/chains/injective.svg',
    rpcUrl: 'https://lb.nodies.app/rpc/injective-mainnet',
    explorerUrl: 'https://explorer.injective.network',
    nativeCurrency: { name: 'Injective', symbol: 'INJ', decimals: 18 },
    isTestnet: false,
    isEnabled: true,
    priority: 54,
    status: 'healthy',
    chainId: 60,
    gasConfig: { type: 'cosmos', gasPrice: '900000000inj', gasLimit: 200000 },
    features: { cosmwasmEnabled: true, ibc: true, dex: true },
  },

  'stargaze:mainnet': {
    id: 'stargaze:mainnet' as any,
    name: 'Stargaze',
    symbol: 'STARS',
    type: 'cosmos',
    icon: '/icons/chains/stargaze.svg',
    rpcUrl: 'https://rpc.cosmos.directory/stargaze',
    explorerUrl: 'https://www.mintscan.io/stargaze',
    nativeCurrency: { name: 'Stargaze', symbol: 'STARS', decimals: 6 },
    isTestnet: false,
    isEnabled: true,
    priority: 55,
    status: 'healthy',
    gasConfig: { type: 'cosmos', gasPrice: '0.0025ustars', gasLimit: 200000 },
    features: { cosmwasmEnabled: true, ibc: true, nft: true },
  },

  'juno:mainnet': {
    id: 'juno:mainnet' as any,
    name: 'Juno',
    symbol: 'JUNO',
    type: 'cosmos',
    icon: '/icons/chains/juno.svg',
    rpcUrl: 'https://rpc.cosmos.directory/juno',
    explorerUrl: 'https://www.mintscan.io/juno',
    nativeCurrency: { name: 'Juno', symbol: 'JUNO', decimals: 6 },
    isTestnet: false,
    isEnabled: true,
    priority: 56,
    status: 'healthy',
    gasConfig: { type: 'cosmos', gasPrice: '0.0025ujuno', gasLimit: 200000 },
    features: { cosmwasmEnabled: true, ibc: true },
  },

  'neutron:mainnet': {
    id: 'neutron:mainnet' as any,
    name: 'Neutron',
    symbol: 'NTRN',
    type: 'cosmos',
    icon: '/icons/chains/neutron.svg',
    rpcUrl: 'https://rpc.cosmos.directory/neutron',
    explorerUrl: 'https://www.mintscan.io/neutron',
    nativeCurrency: { name: 'Neutron', symbol: 'NTRN', decimals: 6 },
    isTestnet: false,
    isEnabled: true,
    priority: 57,
    status: 'healthy',
    gasConfig: { type: 'cosmos', gasPrice: '0.0025untrn', gasLimit: 200000 },
    features: { cosmwasmEnabled: true, ibc: true, interchain: true },
  },

  'dydx:mainnet': {
    id: 'dydx:mainnet' as any,
    name: 'dYdX',
    symbol: 'DYDX',
    type: 'cosmos',
    icon: '/icons/chains/dydx.svg',
    rpcUrl: 'https://dydx-mainnet-lcd.allthatnode.com:1317',
    explorerUrl: 'https://www.mintscan.io/dydx',
    nativeCurrency: { name: 'dYdX', symbol: 'DYDX', decimals: 18 },
    isTestnet: false,
    isEnabled: true,
    priority: 58,
    status: 'healthy',
    chainId: 25,
    gasConfig: { type: 'cosmos', gasPrice: '12500000000adydx', gasLimit: 200000 },
    features: { cosmwasmEnabled: false, ibc: true, perpetuals: true },
  },

  // TON
  'ton:mainnet': {
    id: 'ton:mainnet' as any,
    name: 'TON Mainnet',
    symbol: 'TON',
    type: 'ton',
    icon: '/icons/chains/ton.svg',
    rpcUrl: 'https://toncenter.com/api/v2/jsonRPC',
    explorerUrl: 'https://tonviewer.com',
    nativeCurrency: { name: 'Toncoin', symbol: 'TON', decimals: 9 },
    isTestnet: false,
    isEnabled: true,
    priority: 59,
    status: 'healthy',
    gasConfig: { type: 'ton', gasPrice: 1000000000, storageFeePerYear: 5000000000 },
    features: { smartContracts: true, jetton: true, nft: true },
  },

  // NEAR
  'near:mainnet': {
    id: 'near:mainnet' as any,
    name: 'NEAR Mainnet',
    symbol: 'NEAR',
    type: 'near',
    icon: '/icons/chains/near.svg',
    rpcUrl: 'https://rpc.mainnet.near.org',
    explorerUrl: 'https://nearblocks.io',
    nativeCurrency: { name: 'NEAR', symbol: 'NEAR', decimals: 24 },
    isTestnet: false,
    isEnabled: true,
    priority: 60,
    status: 'healthy',
    gasConfig: { type: 'near', gasPrice: 100000000, attachedDeposit: 0 },
    features: { sharding: true, crossContract: true, fungibleToken: true },
  },

  // TRON
  'tron:mainnet': {
    id: 'tron:mainnet' as any,
    name: 'TRON Mainnet',
    symbol: 'TRX',
    type: 'tron',
    icon: '/icons/chains/tron.svg',
    rpcUrl: 'https://api.tronstack.io',
    explorerUrl: 'https://tronscan.org',
    nativeCurrency: { name: 'Tronix', symbol: 'TRX', decimals: 6 },
    isTestnet: false,
    isEnabled: true,
    priority: 61,
    status: 'healthy',
    gasConfig: { type: 'tron', feeLimit: 100000000, energyPrice: 280 },
    features: { smartContracts: true, trc20: true, trc721: true },
  },

  // CARDANO
  'cardano:mainnet': {
    id: 'cardano:mainnet' as any,
    name: 'Cardano Mainnet',
    symbol: 'ADA',
    type: 'cardano',
    icon: '/icons/chains/cardano.svg',
    rpcUrl: 'https://cardano-mainnet.blockfrost.io/api/v0',
    explorerUrl: 'https://cexplorer.io',
    nativeCurrency: { name: 'Lovelace', symbol: 'ADA', decimals: 6 },
    isTestnet: false,
    isEnabled: true,
    priority: 62,
    status: 'healthy',
    gasConfig: { type: 'bitcoin', minFeeA: 44, minFeeB: 155381, maxTxSize: 16384 },
    features: { utxo: true, smartContracts: true, plutus: true },
  },

  // SUBSTRATE / POLKADOT ECOSYSTEM
  'polkadot:mainnet': {
    id: 'polkadot:mainnet' as any,
    name: 'Polkadot',
    symbol: 'DOT',
    type: 'substrate',
    icon: '/icons/chains/polkadot.svg',
    rpcUrl: 'wss://rpc.polkadot.io',
    explorerUrl: 'https://polkadot.subscan.io',
    nativeCurrency: { name: 'Polkadot', symbol: 'DOT', decimals: 10 },
    isTestnet: false,
    isEnabled: true,
    priority: 63,
    status: 'healthy',
    gasConfig: { type: 'bitcoin', weightPerGas: 1, existentialDeposit: 1000000000 },
    features: { parachains: true, xcmp: true, governance: true },
  },

  'kusama:mainnet': {
    id: 'kusama:mainnet' as any,
    name: 'Kusama',
    symbol: 'KSM',
    type: 'substrate',
    icon: '/icons/chains/kusama.svg',
    rpcUrl: 'wss://kusama-rpc.polkadot.io',
    explorerUrl: 'https://kusama.subscan.io',
    nativeCurrency: { name: 'Kusama', symbol: 'KSM', decimals: 12 },
    isTestnet: false,
    isEnabled: true,
    priority: 64,
    status: 'healthy',
    gasConfig: { type: 'bitcoin', weightPerGas: 1, existentialDeposit: 333333 },
    features: { parachains: true, xcmp: true, governance: true },
  },

  'astar:mainnet': {
    id: 'astar:mainnet' as any,
    name: 'Astar',
    symbol: 'ASTR',
    type: 'substrate',
    icon: '/icons/chains/astar.svg',
    rpcUrl: 'https://rpc.astar.network',
    explorerUrl: 'https://astar.subscan.io',
    nativeCurrency: { name: 'Astar', symbol: 'ASTR', decimals: 18 },
    isTestnet: false,
    isEnabled: true,
    priority: 65,
    status: 'healthy',
    chainId: 592,
    gasConfig: { type: 'bitcoin', weightPerGas: 1, existentialDeposit: 0 },
    features: { parachains: true, xcmp: true, wasmSmartContracts: true },
  },

  'moonbeam:mainnet': {
    id: 'moonbeam:mainnet' as any,
    name: 'Moonbeam',
    symbol: 'GLMR',
    type: 'substrate',
    icon: '/icons/chains/moonbeam.svg',
    rpcUrl: 'https://rpc.api.moonbeam.network',
    explorerUrl: 'https://moonscan.io',
    nativeCurrency: { name: 'Moonbeam', symbol: 'GLMR', decimals: 18 },
    isTestnet: false,
    isEnabled: true,
    priority: 66,
    status: 'healthy',
    chainId: 1284,
    gasConfig: { type: 'eip1559', maxFeePerGas: 100, maxPriorityFeePerGas: 1 },
    features: { parachains: true, xcmp: true, evmCompatible: true },
  },

  'equilibrium:mainnet': {
    id: 'equilibrium:mainnet' as any,
    name: 'Equilibrium',
    symbol: 'EQ',
    type: 'substrate',
    icon: '/icons/chains/equilibrium.svg',
    rpcUrl: 'https://mainnet.equilibrium.io',
    explorerUrl: 'https://equilibrium.subscan.io',
    nativeCurrency: { name: 'Equilibrium', symbol: 'EQ', decimals: 9 },
    isTestnet: false,
    isEnabled: true,
    priority: 67,
    status: 'healthy',
    gasConfig: { type: 'bitcoin', weightPerGas: 1, existentialDeposit: 0 },
    features: { parachains: true, xcmp: true, lending: true },
  },
};
