[package]
name = "transaction-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenv.workspace = true
uuid.workspace = true
chrono.workspace = true
redis.workspace = true
rust_decimal.workspace = true
thiserror.workspace = true
tower-http.workspace = true

[[bin]]
name = "transaction-service"
path = "src/main.rs"